const posterUrls={m1:'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',m2:'https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg',m3:'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',m4:'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',m5:'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',m6:'https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg',m7:'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',m8:'https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',m9:'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',m10:'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'};
const movies=[
{id:'m1',title:'Past Lives',year:2023,genres:['Romance','Drama'],director:'Celine Song',actors:['Greta Lee','Teo Yoo'],rating:4.8,poster:'poster-a',reason:'Because you love intimate stories',plot:'Two childhood friends reunite in New York for one fateful week, asking what might have been.'},
{id:'m2',title:'The Holdovers',year:2023,genres:['Comedy','Drama'],director:'Alexander Payne',actors:['Paul Giamatti','Da’Vine Joy Randolph'],rating:4.7,poster:'poster-b',reason:'Shared emotional DNA',plot:'A cranky teacher, a grieving cook, and a stranded student find an unlikely family over winter break.'},
{id:'m3',title:'Aftersun',year:2022,genres:['Drama'],director:'Charlotte Wells',actors:['Paul Mescal','Frankie Corio'],rating:4.6,poster:'poster-c',reason:'Your quiet-beautiful signal',plot:'A daughter looks back on a holiday with her young father and the memories that linger.'},
{id:'m4',title:'The Worst Person in the World',year:2021,genres:['Romance','Comedy'],director:'Joachim Trier',actors:['Renate Reinsve','Anders Danielsen Lie'],rating:4.5,poster:'poster-d',reason:'A little messy, very human',plot:'Four years in the life of a young woman navigating the troubled waters of her love life.'},
{id:'m5',title:'Anatomy of a Fall',year:2023,genres:['Drama','Mystery'],director:'Justine Triet',actors:['Sandra Hüller','Swann Arlaud'],rating:4.6,poster:'poster-e',reason:'For your curious side',plot:'A woman is suspected of her husband’s murder, and their blind son faces a moral dilemma.'},
{id:'m6',title:'The Grand Budapest Hotel',year:2014,genres:['Comedy','Adventure'],director:'Wes Anderson',actors:['Ralph Fiennes','Tony Revolori'],rating:4.4,poster:'poster-f',reason:'Your visual storytelling branch',plot:'A legendary concierge and his lobby boy become ensnared in a theft and a family fortune.'},
{id:'m7',title:'Decision to Leave',year:2022,genres:['Mystery','Romance'],director:'Park Chan-wook',actors:['Park Hae-il','Tang Wei'],rating:4.4,poster:'poster-a',reason:'Because you liked mysteries',plot:'A detective investigating a man’s death falls for the dead man’s mysterious wife.'},
{id:'m8',title:'Perfect Days',year:2023,genres:['Drama'],director:'Wim Wenders',actors:['Koji Yakusho','Yumi Aso'],rating:4.5,poster:'poster-b',reason:'A slow-burn discovery',plot:'A Tokyo toilet cleaner finds beauty in the small rituals of his carefully structured days.'},
{id:'m9',title:'Spider-Man: Across the Spider-Verse',year:2023,genres:['Animation','Adventure'],director:'Joaquim Dos Santos',actors:['Shameik Moore','Hailee Steinfeld'],rating:4.7,poster:'poster-c',reason:'Popular in your network',plot:'Miles Morales catapults across the Multiverse and encounters a team charged with protecting its existence.'},
{id:'m10',title:'Oppenheimer',year:2023,genres:['Drama','History'],director:'Christopher Nolan',actors:['Cillian Murphy','Emily Blunt'],rating:4.5,poster:'poster-d',reason:'Trending near you',plot:'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.'}
];
const rated={m1:5,m3:5,m6:4,m8:4};let library=new Set(Object.keys(rated));let currentMode='for-you';
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function card(movie){return `<article class="movie-card" data-id="${movie.id}"><div class="poster ${movie.poster}" style="background-image:url('${posterUrls[movie.id]}')">${movie.reason?`<span class="movie-badge">✦ ${movie.reason}</span>`:''}</div><div class="movie-info"><span class="rating">★ ${movie.rating}</span><h3>${movie.title}</h3><p>${movie.year} · ${movie.genres.join(' / ')}</p></div></article>`}
function renderRecommendations(){let list=currentMode==='popular'?[...movies].sort((a,b)=>b.rating-a.rating):currentMode==='because'?[movies[6],movies[4],movies[1],movies[3]]:[movies[0],movies[1],movies[2],movies[3]];$('#recommendation-grid').innerHTML=list.map(card).join('');bindCards()}
function renderCatalog(query=''){let list=movies.filter(m=>(m.title+' '+m.genres.join(' ')+' '+m.actors.join(' ')+' '+m.director).toLowerCase().includes(query.toLowerCase()));$('#catalog-grid').innerHTML=list.map(card).join('');bindCards()}
function renderLibrary(){let list=movies.filter(m=>library.has(m.id));$('#library-grid').innerHTML=list.length?list.map(card).join(''):'<p class="empty-state">Your shelf is waiting for a story.</p>';$('#library-count').textContent=list.length;bindCards()}
function bindCards(){$$('.movie-card').forEach(c=>c.addEventListener('click',()=>openMovie(c.dataset.id)))}
function openMovie(id){const m=movies.find(x=>x.id===id);$('#modal-content').innerHTML=`<div class="modal-poster poster ${m.poster}"></div><p class="eyebrow">${m.year} · ${m.genres.join(' / ')}</p><h2>${m.title}</h2><p class="modal-meta">Directed by ${m.director}<br>Starring ${m.actors.join(', ')}<br><span class="rating">★ ${m.rating}</span></p><p class="modal-copy">${m.plot}</p><div class="rating-actions"><button data-rate="5">★ Loved it</button><button data-rate="4">Liked it</button><button data-save>${library.has(m.id)?'✓ In your library':'＋ Add to library'}</button></div>`;$('#movie-modal').classList.add('open');$$('[data-rate]').forEach(b=>b.onclick=()=>{rated[id]=Number(b.dataset.rate);library.add(id);renderLibrary();toast(`Rated ${m.title} ${b.dataset.rate}/5`);$('#movie-modal').classList.remove('open')});$('[data-save]').onclick=()=>{library.has(id)?library.delete(id):library.add(id);renderLibrary();openMovie(id);toast(library.has(id)?'Added to your library':'Removed from your library')}}
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function setupNav(){$$('.nav-item').forEach(button=>button.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');$$('.view').forEach(v=>v.classList.remove('active-view'));$(`#${button.dataset.view}-view`).classList.add('active-view');if(button.dataset.view==='network')drawGraph();if(innerWidth<651)$('.sidebar').classList.remove('open')});$$('.mood').forEach(button=>button.onclick=()=>{$$('.mood').forEach(x=>x.classList.remove('active'));button.classList.add('active');toast(`${button.textContent.trim()} mode selected`)});$('.mobile-menu').onclick=()=>$('.sidebar').classList.toggle('open')}
function drawGraph(){const canvas=$('#graph-canvas'),box=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=box.width*d;canvas.height=box.height*d;const ctx=canvas.getContext('2d');ctx.scale(d,d);const w=box.width,h=box.height;const nodes=[{x:w*.5,y:h*.48,r:31,label:'Meet',type:'user'},{x:w*.25,y:h*.28,r:25,label:'Past Lives',type:'movie'},{x:w*.74,y:h*.25,r:25,label:'Aftersun',type:'movie'},{x:w*.8,y:h*.66,r:25,label:'Perfect Days',type:'movie'},{x:w*.27,y:h*.76,r:25,label:'Drama',type:'genre'},{x:w*.5,y:h*.12,r:22,label:'Romance',type:'genre'},{x:w*.12,y:h*.53,r:22,label:'Celine Song',type:'genre'},{x:w*.94,y:h*.43,r:22,label:'Wim Wenders',type:'genre'}];const links=[[0,1],[0,2],[0,3],[1,4],[1,5],[1,6],[2,4],[2,5],[3,4],[3,7]];ctx.lineWidth=1;links.forEach(([a,b])=>{ctx.strokeStyle='#4c535d';ctx.beginPath();ctx.moveTo(nodes[a].x,nodes[a].y);ctx.lineTo(nodes[b].x,nodes[b].y);ctx.stroke()});nodes.forEach(n=>{ctx.shadowBlur=n.type==='user'?18:8;ctx.shadowColor=n.type==='user'?'#e66b4e':'transparent';ctx.fillStyle=n.type==='user'?'#e66b4e':n.type==='movie'?'#b3a9dc':'#f0ba55';ctx.beginPath();ctx.arc(n.x,n.y,n.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#fff';ctx.font=`${n.type==='user'?11:9}px Manrope`;ctx.textAlign='center';ctx.fillText(n.label,n.x,n.y+n.r+16)});}
$$('.segment').forEach(b=>b.onclick=()=>{$$('.segment').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentMode=b.dataset.mode;renderRecommendations()});$('#search-input').oninput=e=>renderCatalog(e.target.value);$('.modal-close').onclick=()=>$('#movie-modal').classList.remove('open');$('#movie-modal').onclick=e=>{if(e.target.id==='movie-modal')$('#movie-modal').classList.remove('open')};$('#reset-graph').onclick=drawGraph;setupNav();renderRecommendations();renderCatalog();renderLibrary();window.onresize=()=>{if($('#network-view').classList.contains('active-view'))drawGraph()};
